version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/provider"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/sdk"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/tests"
    schedule:
      interval: "daily"
