linters:
  enable:
    - errcheck
    - goconst
    - gofmt
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unconvert
    - revive
  enable-all: false

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-files:
    - schema.go
    - pulumiManifest.go
run:
  timeout: 20m
