archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - go mod tidy
builds:
  - binary: pulumi-resource-grid
    dir: internal
    main: ../main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: "arm64"
      - goos: windows
        goarch: "arm"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  skip: true
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
