archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - go mod tidy
builds:
  - binary: pulumi-resource-grid
    dir: provider
    main: ./cmd/pulumi-resource-grid/main.go
    ldflags:
      - -X github.com/threefoldtech/pulumi-provider-grid/provider/cmd/pulumi-resource-grid/main.Version={{.Tag }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: "arm64"
      - goos: windows
        goarch: "arm"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  skip: true
