name: pulumi-provider-grid
runtime: yaml

plugins:
  providers:
    - name: grid
      path: ../..

resources:
  provider:
    type: pulumi:providers:grid
    properties:
      type: sr25519
      mnemonic:

  network:
    type: grid:internal:Network
    options:
      provider: ${provider}
    properties:
      name: test
      description: test network
      nodes:
        - 3
      ip_range: 10.1.0.0/16
      add_wg_access: true
      solution_type: Network

  kubernetes:
    type: grid:internal:Kubernetes
    options:
      provider: ${provider}
    properties:
      master:
        name: mr
        node: 3
        disk_size: 2
        publicip: true
        cpu: 2
        memory: 2048

      workers:
        - name: w0
          node: 3
          disk_size: 2
          cpu: 2
          memory: 2048
        - name: w1
          node: 3
          disk_size: 2
          cpu: 2
          memory: 2048

      token: t123456789
      network_name: test

outputs:
  node_deployment_id: ${kubernetes.node_deployment_id}
