name: pulumi-threefold
runtime: yaml

# # local build
# plugins:
#   providers:
#     - name: threefold
#       path: ../../../bin

resources:
  random:
    type: random:RandomString
    properties:
      length: 8
      special: false

  provider:
    type: pulumi:providers:threefold
    options:
      pluginDownloadURL: github://api.github.com/threefoldtech/pulumi-threefold # optional
    properties:
      mnemonic:

  scheduler:
    type: threefold:Scheduler
    options:
      provider: ${provider}
    properties:
      mru: 6
      sru: 6
      farm_ids: [1]
      ygg: true

  network:
    type: threefold:Network
    options:
      provider: ${provider}
      dependsOn:
        - ${scheduler}
    properties:
      name: net_${random.result}
      description: test network
      nodes:
        - ${scheduler.nodes[0]}
      ip_range: 10.1.0.0/16
      mycelium: true

  kubernetes:
    type: threefold:Kubernetes
    options:
      provider: ${provider}
      dependsOn:
        - ${network}
    properties:
      master:
        name: kubernetes_${random.result}
        network_name: net_${random.result}
        node_id: ${scheduler.nodes[0]}
        disk_size: 2
        planetary: true
        mycelium: true
        cpu: 2
        memory: 2048

      workers:
        - name: worker1_${random.result}
          network_name: net_${random.result}
          node_id: ${scheduler.nodes[0]}
          disk_size: 2
          cpu: 2
          memory: 2048
          mycelium: true
        - name: worker2_${random.result}
          network_name: net_${random.result}
          node_id: ${scheduler.nodes[0]}
          disk_size: 2
          cpu: 2
          memory: 2048
          mycelium: true

      token: t123456789
      network_name: net_${random.result}
      ssh_key:

outputs:
  node_deployment_id: ${kubernetes.node_deployment_id}
  planetary_ip: ${kubernetes.master_computed.planetary_ip}
  mycelium_ip: ${kubernetes.master_computed.mycelium_ip}
