name: integration

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["dev"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go get -d ./...

      - name: Build provider
        run: go build -o pulumi-resource-grid github.com/threefoldtech/pulumi-provider-grid

      - name: Run Tests
        run: go test -v ./tests
        env:
          MNEMONICS: ${{ secrets.MNEMONIC }}
          NETWORK: ${{ matrix.network }}
