name: integration tests for latest version

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["dev", "qa", "test", "main"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: install curl, wg and yggdrasil and add peers
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard
          sudo apt-get install dirmngr
          sudo apt-get install curl
          wget https://github.com/threefoldtech/mycelium/releases/download/v0.5.4/mycelium-x86_64-unknown-linux-musl.tar.gz
          tar xzf mycelium-x86_64-unknown-linux-musl.tar.gz
          sudo ./mycelium --peers tcp://188.40.132.242:9651 quic://185.69.166.8:9651 --tun-name utun9 -k /tmp/mycelium_priv_key.bin &

      - name: Install provider
        run: make install_latest

      - name: Run Tests for yaml examples
        run: go test -v ./tests
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          NETWORK: ${{ matrix.network }}
          EXAMPLES: ../examples/yaml

      - name: Run Tests for go examples
        run: go test -v ./tests
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          NETWORK: ${{ matrix.network }}
          EXAMPLES: ../examples/go

      - name: Run Tests for python examples
        run: go test -v ./tests
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          NETWORK: ${{ matrix.network }}
          EXAMPLES: ../examples/python

      - name: Run Tests for nodejs examples
        run: go test -v ./tests
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          NETWORK: ${{ matrix.network }}
          EXAMPLES: ../examples/nodejs
