name: integration tests for latest version

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["dev", "qa", "test", "main"]
        lang: ["yaml", "go", "python"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: install curl, wg and yggdrasil and add peers
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard
          sudo apt-get install dirmngr
          sudo apt-get install curl
          gpg --fetch-keys https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
          gpg --export 569130E8CA20FBC4CB3FDE555898470A764B32C9 | sudo apt-key add -
          echo 'deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil' | sudo tee /etc/apt/sources.list.d/yggdrasil.list
          sudo apt-get update
          sudo apt-get install yggdrasil
          sudo systemctl enable yggdrasil
          PEERS=$(curl https://raw.githubusercontent.com/AhmedHanafy725/yggdrasil-config/main/config.json | jq '.yggdrasil.peers[]' -r | sed 's/\//\\\//g' | sed -z 's/\n/\\n/g')
          sudo sed -i -- 's/Peers\: \[\]/Peers: [\n'"$PEERS"']/g' /etc/yggdrasil/yggdrasil.conf
          sudo systemctl stop yggdrasil
          sudo systemctl start yggdrasil

      - name: Install provider
        run: make install_latest

      - name: Run Tests for ${{ matrix.lang }} examples
        run: go test -v ./tests
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          NETWORK: ${{ matrix.network }}
          EXAMPLES: ../examples/${{ matrix.lang }}
